hooks: Add missing build-essentials dependency.
When attempting to build a rust project using this SDK, before
this change you would get errors similar to this:

    error: linker `cc` not found
      |
      = note: No such file or directory (os error 2)

If you only install gcc and libc6-dev you will still get errors like:

    error: linking with `cc` failed: exit status: 1

[ snip ]
      = note: rust-lld: error: cannot open Scrt1.o: No such file or directory
              rust-lld: error: cannot open crti.o: No such file or directory
              rust-lld: error: unable to find library -lutil
              rust-lld: error: unable to find library -lrt
              rust-lld: error: unable to find library -lpthread
              rust-lld: error: unable to find library -lm
              rust-lld: error: unable to find library -ldl
              rust-lld: error: unable to find library -lc
              rust-lld: error: cannot open crtn.o: No such file or directory
              collect2: error: ld returned 1 exit status

If we install build-essential, the issue goes away.

Signed-off-by: Frode Nordahl <fnordahl@ubuntu.com>